// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models.proto

package io.fizz.chat.user.infrastructure.persistence;

public final class Models {
  private Models() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlatformTokensOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hbaseClient.PlatformTokens)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string token = 1;</code>
     */
    java.util.List<java.lang.String>
        getTokenList();
    /**
     * <code>repeated string token = 1;</code>
     */
    int getTokenCount();
    /**
     * <code>repeated string token = 1;</code>
     */
    java.lang.String getToken(int index);
    /**
     * <code>repeated string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes(int index);
  }
  /**
   * Protobuf type {@code hbaseClient.PlatformTokens}
   */
  public  static final class PlatformTokens extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hbaseClient.PlatformTokens)
      PlatformTokensOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlatformTokens.newBuilder() to construct.
    private PlatformTokens(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlatformTokens() {
      token_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlatformTokens(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                token_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              token_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          token_ = token_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.fizz.chat.user.infrastructure.persistence.Models.internal_static_hbaseClient_PlatformTokens_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.fizz.chat.user.infrastructure.persistence.Models.internal_static_hbaseClient_PlatformTokens_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens.class, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens.Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList token_;
    /**
     * <code>repeated string token = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTokenList() {
      return token_;
    }
    /**
     * <code>repeated string token = 1;</code>
     */
    public int getTokenCount() {
      return token_.size();
    }
    /**
     * <code>repeated string token = 1;</code>
     */
    public java.lang.String getToken(int index) {
      return token_.get(index);
    }
    /**
     * <code>repeated string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes(int index) {
      return token_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < token_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < token_.size(); i++) {
          dataSize += computeStringSizeNoTag(token_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTokenList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens)) {
        return super.equals(obj);
      }
      io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens other = (io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens) obj;

      boolean result = true;
      result = result && getTokenList()
          .equals(other.getTokenList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTokenCount() > 0) {
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getTokenList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hbaseClient.PlatformTokens}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hbaseClient.PlatformTokens)
        io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokensOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.fizz.chat.user.infrastructure.persistence.Models.internal_static_hbaseClient_PlatformTokens_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.fizz.chat.user.infrastructure.persistence.Models.internal_static_hbaseClient_PlatformTokens_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens.class, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens.Builder.class);
      }

      // Construct using io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        token_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.fizz.chat.user.infrastructure.persistence.Models.internal_static_hbaseClient_PlatformTokens_descriptor;
      }

      @java.lang.Override
      public io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens getDefaultInstanceForType() {
        return io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens.getDefaultInstance();
      }

      @java.lang.Override
      public io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens build() {
        io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens buildPartial() {
        io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens result = new io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          token_ = token_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.token_ = token_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens) {
          return mergeFrom((io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens other) {
        if (other == io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens.getDefaultInstance()) return this;
        if (!other.token_.isEmpty()) {
          if (token_.isEmpty()) {
            token_ = other.token_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTokenIsMutable();
            token_.addAll(other.token_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList token_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTokenIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          token_ = new com.google.protobuf.LazyStringArrayList(token_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string token = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTokenList() {
        return token_.getUnmodifiableView();
      }
      /**
       * <code>repeated string token = 1;</code>
       */
      public int getTokenCount() {
        return token_.size();
      }
      /**
       * <code>repeated string token = 1;</code>
       */
      public java.lang.String getToken(int index) {
        return token_.get(index);
      }
      /**
       * <code>repeated string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes(int index) {
        return token_.getByteString(index);
      }
      /**
       * <code>repeated string token = 1;</code>
       */
      public Builder setToken(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTokenIsMutable();
        token_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string token = 1;</code>
       */
      public Builder addToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTokenIsMutable();
        token_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string token = 1;</code>
       */
      public Builder addAllToken(
          java.lang.Iterable<java.lang.String> values) {
        ensureTokenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, token_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string token = 1;</code>
       */
      public Builder clearToken() {
        token_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string token = 1;</code>
       */
      public Builder addTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTokenIsMutable();
        token_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:hbaseClient.PlatformTokens)
    }

    // @@protoc_insertion_point(class_scope:hbaseClient.PlatformTokens)
    private static final io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens();
    }

    public static io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlatformTokens>
        PARSER = new com.google.protobuf.AbstractParser<PlatformTokens>() {
      @java.lang.Override
      public PlatformTokens parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlatformTokens(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlatformTokens> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlatformTokens> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProfileModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hbaseClient.ProfileModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string appId = 1;</code>
     */
    java.lang.String getAppId();
    /**
     * <code>string appId = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppIdBytes();

    /**
     * <code>string userId = 2;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>string userId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string nick = 3;</code>
     */
    java.lang.String getNick();
    /**
     * <code>string nick = 3;</code>
     */
    com.google.protobuf.ByteString
        getNickBytes();

    /**
     * <code>string statusMessage = 4;</code>
     */
    java.lang.String getStatusMessage();
    /**
     * <code>string statusMessage = 4;</code>
     */
    com.google.protobuf.ByteString
        getStatusMessageBytes();

    /**
     * <code>string profileUrl = 5;</code>
     */
    java.lang.String getProfileUrl();
    /**
     * <code>string profileUrl = 5;</code>
     */
    com.google.protobuf.ByteString
        getProfileUrlBytes();

    /**
     * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
     */
    int getTokensCount();
    /**
     * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
     */
    boolean containsTokens(
        java.lang.String key);
    /**
     * Use {@link #getTokensMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens>
    getTokens();
    /**
     * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
     */
    java.util.Map<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens>
    getTokensMap();
    /**
     * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
     */

    io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens getTokensOrDefault(
        java.lang.String key,
        io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens defaultValue);
    /**
     * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
     */

    io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens getTokensOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code hbaseClient.ProfileModel}
   */
  public  static final class ProfileModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:hbaseClient.ProfileModel)
      ProfileModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProfileModel.newBuilder() to construct.
    private ProfileModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProfileModel() {
      appId_ = "";
      userId_ = "";
      nick_ = "";
      statusMessage_ = "";
      profileUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProfileModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              appId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              nick_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              statusMessage_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              profileUrl_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                tokens_ = com.google.protobuf.MapField.newMapField(
                    TokensDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens>
              tokens__ = input.readMessage(
                  TokensDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              tokens_.getMutableMap().put(
                  tokens__.getKey(), tokens__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.fizz.chat.user.infrastructure.persistence.Models.internal_static_hbaseClient_ProfileModel_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetTokens();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.fizz.chat.user.infrastructure.persistence.Models.internal_static_hbaseClient_ProfileModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel.class, io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel.Builder.class);
    }

    private int bitField0_;
    public static final int APPID_FIELD_NUMBER = 1;
    private volatile java.lang.Object appId_;
    /**
     * <code>string appId = 1;</code>
     */
    public java.lang.String getAppId() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appId_ = s;
        return s;
      }
    }
    /**
     * <code>string appId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppIdBytes() {
      java.lang.Object ref = appId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private volatile java.lang.Object userId_;
    /**
     * <code>string userId = 2;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICK_FIELD_NUMBER = 3;
    private volatile java.lang.Object nick_;
    /**
     * <code>string nick = 3;</code>
     */
    public java.lang.String getNick() {
      java.lang.Object ref = nick_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nick_ = s;
        return s;
      }
    }
    /**
     * <code>string nick = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNickBytes() {
      java.lang.Object ref = nick_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nick_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUSMESSAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object statusMessage_;
    /**
     * <code>string statusMessage = 4;</code>
     */
    public java.lang.String getStatusMessage() {
      java.lang.Object ref = statusMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statusMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string statusMessage = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStatusMessageBytes() {
      java.lang.Object ref = statusMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROFILEURL_FIELD_NUMBER = 5;
    private volatile java.lang.Object profileUrl_;
    /**
     * <code>string profileUrl = 5;</code>
     */
    public java.lang.String getProfileUrl() {
      java.lang.Object ref = profileUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        profileUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string profileUrl = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProfileUrlBytes() {
      java.lang.Object ref = profileUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profileUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKENS_FIELD_NUMBER = 6;
    private static final class TokensDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens>newDefaultInstance(
                  io.fizz.chat.user.infrastructure.persistence.Models.internal_static_hbaseClient_ProfileModel_TokensEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> tokens_;
    private com.google.protobuf.MapField<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens>
    internalGetTokens() {
      if (tokens_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TokensDefaultEntryHolder.defaultEntry);
      }
      return tokens_;
    }

    public int getTokensCount() {
      return internalGetTokens().getMap().size();
    }
    /**
     * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
     */

    public boolean containsTokens(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTokens().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTokensMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> getTokens() {
      return getTokensMap();
    }
    /**
     * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
     */

    public java.util.Map<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> getTokensMap() {
      return internalGetTokens().getMap();
    }
    /**
     * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
     */

    public io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens getTokensOrDefault(
        java.lang.String key,
        io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> map =
          internalGetTokens().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
     */

    public io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens getTokensOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> map =
          internalGetTokens().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      if (!getNickBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nick_);
      }
      if (!getStatusMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, statusMessage_);
      }
      if (!getProfileUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, profileUrl_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTokens(),
          TokensDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appId_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      if (!getNickBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nick_);
      }
      if (!getStatusMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, statusMessage_);
      }
      if (!getProfileUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, profileUrl_);
      }
      for (java.util.Map.Entry<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> entry
           : internalGetTokens().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens>
        tokens__ = TokensDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, tokens__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel)) {
        return super.equals(obj);
      }
      io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel other = (io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel) obj;

      boolean result = true;
      result = result && getAppId()
          .equals(other.getAppId());
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getNick()
          .equals(other.getNick());
      result = result && getStatusMessage()
          .equals(other.getStatusMessage());
      result = result && getProfileUrl()
          .equals(other.getProfileUrl());
      result = result && internalGetTokens().equals(
          other.internalGetTokens());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPID_FIELD_NUMBER;
      hash = (53 * hash) + getAppId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + NICK_FIELD_NUMBER;
      hash = (53 * hash) + getNick().hashCode();
      hash = (37 * hash) + STATUSMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusMessage().hashCode();
      hash = (37 * hash) + PROFILEURL_FIELD_NUMBER;
      hash = (53 * hash) + getProfileUrl().hashCode();
      if (!internalGetTokens().getMap().isEmpty()) {
        hash = (37 * hash) + TOKENS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTokens().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hbaseClient.ProfileModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hbaseClient.ProfileModel)
        io.fizz.chat.user.infrastructure.persistence.Models.ProfileModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.fizz.chat.user.infrastructure.persistence.Models.internal_static_hbaseClient_ProfileModel_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetTokens();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableTokens();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.fizz.chat.user.infrastructure.persistence.Models.internal_static_hbaseClient_ProfileModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel.class, io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel.Builder.class);
      }

      // Construct using io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        appId_ = "";

        userId_ = "";

        nick_ = "";

        statusMessage_ = "";

        profileUrl_ = "";

        internalGetMutableTokens().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.fizz.chat.user.infrastructure.persistence.Models.internal_static_hbaseClient_ProfileModel_descriptor;
      }

      @java.lang.Override
      public io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel getDefaultInstanceForType() {
        return io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel.getDefaultInstance();
      }

      @java.lang.Override
      public io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel build() {
        io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel buildPartial() {
        io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel result = new io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.appId_ = appId_;
        result.userId_ = userId_;
        result.nick_ = nick_;
        result.statusMessage_ = statusMessage_;
        result.profileUrl_ = profileUrl_;
        result.tokens_ = internalGetTokens();
        result.tokens_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel) {
          return mergeFrom((io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel other) {
        if (other == io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel.getDefaultInstance()) return this;
        if (!other.getAppId().isEmpty()) {
          appId_ = other.appId_;
          onChanged();
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getNick().isEmpty()) {
          nick_ = other.nick_;
          onChanged();
        }
        if (!other.getStatusMessage().isEmpty()) {
          statusMessage_ = other.statusMessage_;
          onChanged();
        }
        if (!other.getProfileUrl().isEmpty()) {
          profileUrl_ = other.profileUrl_;
          onChanged();
        }
        internalGetMutableTokens().mergeFrom(
            other.internalGetTokens());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object appId_ = "";
      /**
       * <code>string appId = 1;</code>
       */
      public java.lang.String getAppId() {
        java.lang.Object ref = appId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppIdBytes() {
        java.lang.Object ref = appId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appId = 1;</code>
       */
      public Builder setAppId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appId = 1;</code>
       */
      public Builder clearAppId() {
        
        appId_ = getDefaultInstance().getAppId();
        onChanged();
        return this;
      }
      /**
       * <code>string appId = 1;</code>
       */
      public Builder setAppIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>string userId = 2;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 2;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 2;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nick_ = "";
      /**
       * <code>string nick = 3;</code>
       */
      public java.lang.String getNick() {
        java.lang.Object ref = nick_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nick_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nick = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNickBytes() {
        java.lang.Object ref = nick_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nick_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nick = 3;</code>
       */
      public Builder setNick(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nick_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nick = 3;</code>
       */
      public Builder clearNick() {
        
        nick_ = getDefaultInstance().getNick();
        onChanged();
        return this;
      }
      /**
       * <code>string nick = 3;</code>
       */
      public Builder setNickBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nick_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object statusMessage_ = "";
      /**
       * <code>string statusMessage = 4;</code>
       */
      public java.lang.String getStatusMessage() {
        java.lang.Object ref = statusMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          statusMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string statusMessage = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStatusMessageBytes() {
        java.lang.Object ref = statusMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statusMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string statusMessage = 4;</code>
       */
      public Builder setStatusMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        statusMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string statusMessage = 4;</code>
       */
      public Builder clearStatusMessage() {
        
        statusMessage_ = getDefaultInstance().getStatusMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string statusMessage = 4;</code>
       */
      public Builder setStatusMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        statusMessage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object profileUrl_ = "";
      /**
       * <code>string profileUrl = 5;</code>
       */
      public java.lang.String getProfileUrl() {
        java.lang.Object ref = profileUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          profileUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string profileUrl = 5;</code>
       */
      public com.google.protobuf.ByteString
          getProfileUrlBytes() {
        java.lang.Object ref = profileUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          profileUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string profileUrl = 5;</code>
       */
      public Builder setProfileUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        profileUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string profileUrl = 5;</code>
       */
      public Builder clearProfileUrl() {
        
        profileUrl_ = getDefaultInstance().getProfileUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string profileUrl = 5;</code>
       */
      public Builder setProfileUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        profileUrl_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> tokens_;
      private com.google.protobuf.MapField<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens>
      internalGetTokens() {
        if (tokens_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TokensDefaultEntryHolder.defaultEntry);
        }
        return tokens_;
      }
      private com.google.protobuf.MapField<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens>
      internalGetMutableTokens() {
        onChanged();;
        if (tokens_ == null) {
          tokens_ = com.google.protobuf.MapField.newMapField(
              TokensDefaultEntryHolder.defaultEntry);
        }
        if (!tokens_.isMutable()) {
          tokens_ = tokens_.copy();
        }
        return tokens_;
      }

      public int getTokensCount() {
        return internalGetTokens().getMap().size();
      }
      /**
       * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
       */

      public boolean containsTokens(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTokens().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTokensMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> getTokens() {
        return getTokensMap();
      }
      /**
       * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
       */

      public java.util.Map<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> getTokensMap() {
        return internalGetTokens().getMap();
      }
      /**
       * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
       */

      public io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens getTokensOrDefault(
          java.lang.String key,
          io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> map =
            internalGetTokens().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
       */

      public io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens getTokensOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> map =
            internalGetTokens().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTokens() {
        internalGetMutableTokens().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
       */

      public Builder removeTokens(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTokens().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens>
      getMutableTokens() {
        return internalGetMutableTokens().getMutableMap();
      }
      /**
       * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
       */
      public Builder putTokens(
          java.lang.String key,
          io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTokens().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .hbaseClient.PlatformTokens&gt; tokens = 6;</code>
       */

      public Builder putAllTokens(
          java.util.Map<java.lang.String, io.fizz.chat.user.infrastructure.persistence.Models.PlatformTokens> values) {
        internalGetMutableTokens().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:hbaseClient.ProfileModel)
    }

    // @@protoc_insertion_point(class_scope:hbaseClient.ProfileModel)
    private static final io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel();
    }

    public static io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProfileModel>
        PARSER = new com.google.protobuf.AbstractParser<ProfileModel>() {
      @java.lang.Override
      public ProfileModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProfileModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProfileModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProfileModel> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.fizz.chat.user.infrastructure.persistence.Models.ProfileModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hbaseClient_PlatformTokens_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hbaseClient_PlatformTokens_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hbaseClient_ProfileModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hbaseClient_ProfileModel_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hbaseClient_ProfileModel_TokensEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hbaseClient_ProfileModel_TokensEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014models.proto\022\013hbaseClient\"\037\n\016PlatformT" +
      "okens\022\r\n\005token\030\001 \003(\t\"\351\001\n\014ProfileModel\022\r\n" +
      "\005appId\030\001 \001(\t\022\016\n\006userId\030\002 \001(\t\022\014\n\004nick\030\003 \001" +
      "(\t\022\025\n\rstatusMessage\030\004 \001(\t\022\022\n\nprofileUrl\030" +
      "\005 \001(\t\0225\n\006tokens\030\006 \003(\0132%.hbaseClient.Prof" +
      "ileModel.TokensEntry\032J\n\013TokensEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022*\n\005value\030\002 \001(\0132\033.hbaseClient.Pl" +
      "atformTokens:\0028\001B6\n,io.fizz.chat.user.in" +
      "frastructure.persistenceB\006Modelsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hbaseClient_PlatformTokens_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hbaseClient_PlatformTokens_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hbaseClient_PlatformTokens_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_hbaseClient_ProfileModel_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hbaseClient_ProfileModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hbaseClient_ProfileModel_descriptor,
        new java.lang.String[] { "AppId", "UserId", "Nick", "StatusMessage", "ProfileUrl", "Tokens", });
    internal_static_hbaseClient_ProfileModel_TokensEntry_descriptor =
      internal_static_hbaseClient_ProfileModel_descriptor.getNestedTypes().get(0);
    internal_static_hbaseClient_ProfileModel_TokensEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hbaseClient_ProfileModel_TokensEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
